[package]
name = "weather-cli"
version = "0.2.0"
authors = ["mark hakansson"]
edition = "2018"

[dependencies]
structopt = "0.3"
dirs = "2.0"
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
toml = "0.5"
anyhow = "1.0"